### ISSUE TITLE
Unable to launch XPipe 1.7.8 on Windows (No cmd.exe access, No Administrator access, Yes PowerShell)

### ISSUE THREAD

**Issue by danlhead** [xpipe-io/xpipe#102]
I'm trying to run xpipe on a Windows machine that doesn't have Administrator privileges nor access to cmd. I do have access to powershell though. I'm getting the error "The pipe is being closed".  Below is the log when running xpiped_debug.bat.

Is this resolvable or is my system too limited?

```
12:54:04:318 - trace: [proc] Writing line {
    line=echo -NoEnumerate "a"
}
12:54:04:379 - trace: [proc] Read: Microsoft Windows [Version 10.0.19045.3570]
12:54:04:380 - trace: [proc] Read: (c) Microsoft Corporation. All rights reserved.
12:54:04:381 - trace: [proc] Read:
12:54:04:383 - trace: [proc] Read: The command prompt has been disabled by your administrator.
12:54:04:384 - trace: [proc] Read:
12:54:04:385 - trace: [proc] Read: Press any key to continue . . .
12:54:14:386 - trace: [proc] Read:  (no LF)
12:54:14:386 - trace: [proc] Writing line {
    line=echo "Checking whether we are in fish"
}
12:54:14:388 - trace: [proc] Killing local shell ...
12:54:14:406 - error: java.io.IOException: The pipe is being closed
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:367)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125)
        at java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:252)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:240)
        at io.xpipe.ext.proc.g.writeLine(SourceFile:37)
        at io.xpipe.ext.proc.util.c.a(SourceFile:137)
        at io.xpipe.ext.proc.d.start(SourceFile:247)
        at io.xpipe.core.store.LocalStore.init(LocalStore.java:23)
        at io.xpipe.app.core.mode.BaseMode.onSwitchTo(BaseMode.java:49)
        at io.xpipe.app.core.mode.OperationMode.set(OperationMode.java:273)
        at io.xpipe.app.core.mode.OperationMode.switchTo(OperationMode.java:142)
        at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:123)
        at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.xpipe.app.launcher.LauncherCommand.runLauncher(LauncherCommand.java:64)
        at io.xpipe.app.core.mode.OperationMode.init(OperationMode.java:114)
        at io.xpipe.app.Main.main(Main.java:15)

12:54:22:117 - info: Loading stylesheets ...
```

**Comment by crschnick** [comment]
That is a case I have not considered yet when cmd is blocked. Administrator privileges are not needed, but cmd is required in order to function right now.

I could evaluate whether it would be possible to run on only powershell though but that would take some time.

Out of curiosity, what is the reason for the cmd block? Is this something you can find more often in organizations than I anticipated?

**Comment by danlhead** [comment]
My client is a government department that runs a fleet of Azure Virtual Desktops. They're used by technical and non-technical users so they don't want users being able to install software or run commands. I manage a number of applications on their servers so they granted me access to Powershell in order to run ssh commands. 

I came across your app on reddit the other other, thought it looked useful for providing a list of my ssh connections in a modern way. Got this error when using the portable Windows app.

**Comment by crschnick** [comment]
Alright, so is PowerShell usage also limited then to only certain commands in your case?

Having access to some shell is required by XPipe to run commands like `ssh` but also to launch terminals and editors, and more.

**Comment by danlhead** [comment]
I don't believe it's been limited in other ways, but I won't know until I try. 
I'm able to run "notepad" and Notepad opens. I'm also able to run "start powershell" and it launches a new Powershell terminal.

**Comment by crschnick** [comment]
That is good news at least, so I should be able to work with that.

I will try to experiment how I can make the cmd dependency optional.

**Comment by crschnick** [comment]
So good news, I experimented with it and I'm confident that this is possible to implement.

This will just take some time, I will let you know when it's ready.

**Comment by crschnick** [comment]
XPipe 8 should now support falling back to powershell exclusively in case cmd does not work

**Comment by danlhead** [comment]
That's awesome! Thanks for your help.

**Comment by crschnick** [comment]
Did you test whether it actually works for you? Because it *should* work, but I didn't test it in an environment like yours.

**Comment by danlhead** [comment]
I just tried it. I initially got a few Null Pointer Exceptions but after clicking Ignore a few times, the app opened and I was able to browse and SSH to my servers. :grinning:

**Comment by crschnick** [comment]
Thanks for the heads up, the null pointers will be fixed in the next release.
