### ISSUE TITLE
SSH File transfer error

### ISSUE THREAD

**Issue by rainrdx** [xpipe-io/xpipe#105]
Hi,

I use this under macos.

The steps to reproduce the error (not sure if necessary) is to:

1. drag a file from the server to the transfer zone on the lower left.
2. drag the file to local.
3. drag a local file to the transfer zone.
and now it says:

java.lang.UnsupportedOperationException: Flush is forbidden from target!

java.lang.UnsupportedOperationException: Flush is forbidden from target!
at com.sun.glass.ui.View$2.flush(View.java:1017)
at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:275)
at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1320)
at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3168)
at javafx.scene.Scene$DnDGesture.process(Scene.java:3237)
at javafx.scene.Scene$MouseHandler.process(Scene.java:4000)
at javafx.scene.Scene.processMouseEvent(Scene.java:1890)
at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
at java.security.AccessController.doPrivileged(AccessController.java:400)
at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
at com.sun.glass.ui.View.notifyMouse(View.java:937)
at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

**Comment by crschnick** [comment]
Is that reproducible? Because I tried and I didn't manage to do it.

But it seems like an JavaFX bug to me, I don't think there's a lot that I can influence here.

**Comment by rainrdx** [comment]
Hmm interesting. It goes away now. when I drag file from local to the transfer zone, nothing happens. the files arent taken in. But this is a very minor issue. Probably not worth your time...

**Comment by crschnick** [comment]
This is actually intended behavior right now to not accept files in the transfer pane.

They are actually intended to be dropped straight into the file list. The transfer pane is just meant for transfers across systems but I can also support local files in it if it is intuitive.

**Comment by rainrdx** [comment]
So it is user error. Yup I am able to drop into the file list and it works. So much appreciate it.
