### ISSUE TITLE
How to fix error below on MacOS M1?

### ISSUE THREAD

**Issue by kienle1819** [xpipe-io/xpipe#120]
io.xpipe.core.process.ProcessOutputException: Process returned exit code 137
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:36)
at io.xpipe.ext.proc.a.a(SourceFile:255)
at io.xpipe.ext.proc.a.discardOrThrow(SourceFile:349)
at io.xpipe.core.process.CommandControl.execute(CommandControl.java:44)
at io.xpipe.core.util.XPipeExecTempDirectory.initExecTempDirectory(XPipeExecTempDirectory.java:47)
at io.xpipe.ext.proc.g.start(SourceFile:270)
at io.xpipe.core.store.LocalStore.init(LocalStore.java:23)
at io.xpipe.app.core.mode.BaseMode.onSwitchTo(BaseMode.java:50)
at io.xpipe.app.core.mode.OperationMode.set(OperationMode.java:301)
at io.xpipe.app.core.mode.OperationMode.switchToSyncOrThrow(OperationMode.java:137)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:127)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:28)
at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
at picocli.CommandLine.execute(CommandLine.java:2170)
at io.xpipe.app.launcher.LauncherCommand.runLauncher(LauncherCommand.java:69)
at io.xpipe.app.core.mode.OperationMode.init(OperationMode.java:115)
at io.xpipe.app.Main.main(Main.java:22)

**Comment by crschnick** [comment]
That indicates that it somehow failed to create the temporary directory. I.e. it tries to execute `mkdir -p ~/.xpipe/temp && chmod 700 ~/.xpipe/temp`.

You can try running it in debug mode with `/Applications/XPipe.app/Contents/Resources/scripts/xpiped_debug.sh` to get more information

**Comment by crschnick** [comment]
Closing this as inactive. Feel free to reopen if there is more information
