### ISSUE TITLE
Installation msi on windows 11 failed (unable to load extension)

### ISSUE THREAD

**Issue by HansDutch62** [xpipe-io/xpipe#121]
Installation failed on Windows 11 (10.0.22621 N/A Build 22621)
Tried with the MSI and Powershell option. 
Stack trace:

io.xpipe.app.ext.ExtensionException: Unable to load extension from directory C:\Users\xxx\AppData\Local\XPipe\app\extensions\base. Is the installation corrupted?
at io.xpipe.app.core.AppExtensionManager.parseExtensionDirectory(AppExtensionManager.java:238)
at io.xpipe.app.core.AppExtensionManager.findAndParseExtension(AppExtensionManager.java:195)
at io.xpipe.app.core.AppExtensionManager.loadBaseExtension(AppExtensionManager.java:61)
at io.xpipe.app.core.AppExtensionManager.init(AppExtensionManager.java:45)
at io.xpipe.app.issue.GuiErrorHandlerBase.startupGui(GuiErrorHandlerBase.java:15)
at io.xpipe.app.issue.TerminalErrorHandler.handle(TerminalErrorHandler.java:25)
at io.xpipe.app.issue.EventHandlerImpl.handle(EventHandlerImpl.java:46)
at io.xpipe.app.issue.ErrorEvent.handle(ErrorEvent.java:66)
at io.xpipe.app.issue.ErrorEvent$ErrorEventBuilder.handle(ErrorEvent.java:99)
at io.xpipe.app.core.AppChecks.checkDirectoryPermissions(AppChecks.java:29)
at io.xpipe.app.core.mode.OperationMode.setup(OperationMode.java:98)
at io.xpipe.app.core.mode.OperationMode.init(OperationMode.java:114)
at io.xpipe.app.Main.main(Main.java:22)

**Comment by crschnick** [comment]
Hmm, I had some previous issues with AntiVirus programs sometimes deleting installation files because they did not like it. How does the directory `C:\Users\xxx\AppData\Local\XPipe\app\extensions\` look like on your end? Is there a `C:\Users\xxx\AppData\Local\XPipe\app\extensions\base\base.jar`?

**Comment by crschnick** [comment]
The MSI and Powershell installation essentially install the same thing. You can try out the portable version, but that one might also have some files deleted if it is indeed an AntiVirus program deleting them

**Comment by HansDutch62** [comment]
base.jar is present in the C:\Users\h.oerlemans\AppData\Local\XPipe\app\extensions\base folder.
Evenvwr doesn't mention anything strange and no other AV then the standard Windows Virus and threat security is installed.
Started allover but sadly with the same result.

**Comment by crschnick** [comment]
Very strange. One thing we could try is launching it in debug mode. If you used the installer, there should be a start menu item called `XPipe Debug` that will print more detailed output.

**Comment by HansDutch62** [comment]
I will close this issue because it's a broader issue. My Bitwarden desktop app has the same/related java issues.
