### ISSUE TITLE
Shell opener fails on Trusnas core (FreeBSD) (sh)

### ISSUE THREAD

**Issue by ascl00** [xpipe-io/xpipe#147]
io.xpipe.core.process.ProcessOutputException: Shell opener command was unsuccessful:
Illegal option -l
at io.xpipe.core.process.ProcessOutputException.withPrefix(ProcessOutputException.java:14)
at io.xpipe.ext.proc.util.c.a(SourceFile:145)
at io.xpipe.ext.proc.m.x(SourceFile:249)
at io.xpipe.ext.proc.m.start(SourceFile:196)
at io.xpipe.core.store.ShellStore.validate(ShellStore.java:31)
at io.xpipe.app.storage.DataStoreEntry.validateOrThrow(DataStoreEntry.java:398)
at io.xpipe.app.storage.DataStoreEntry.validate(DataStoreEntry.java:387)
at io.xpipe.ext.proc.env.l.a(SourceFile:37)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$1(ScanAlert.java:158)
at io.xpipe.app.util.BooleanScope.execute(BooleanScope.java:11)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$2(ScanAlert.java:146)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)

**Comment by crschnick** [comment]
What kind of `sh` is that? Some kind of busybox?

**Comment by ascl00** [comment]
Standard original FreeBSD /bin/sh, not busybox. Man page is here (note no -l):

https://man.freebsd.org/cgi/man.cgi?sh

Source code here: https://github.com/freebsd/freebsd-src/tree/main/bin/sh

**Comment by crschnick** [comment]
Hmm I see. Usually most sh implementations at least allow the `-l` switch even if I does not do anything to provide some compatibility.

I will see what I can do to fix it

**Comment by ascl00** [comment]
I think -l is a bash thing, rather than an sh thing, it's just a lot of linux distro's use bash as sh, ie:
$ ls -la /usr/bin/sh
lrwxrwxrwx 1 root root 4 Apr 25  2023 /usr/bin/sh -> bash

Pure sh even on linux doesn't seem to have an -l option: https://www.man7.org/linux/man-pages/man1/sh.1p.html

**Comment by crschnick** [comment]
Can you try whether the latest PTB works for you: https://github.com/xpipe-io/xpipe-ptb ? Implemented a fix but did not have the time yet to properly test it everywhere.

**Comment by ascl00** [comment]
Certainly! Unfortunately I see the same thing:
io.xpipe.core.process.ProcessOutputException: Shell opener command was unsuccessful:
Illegal option -l
at io.xpipe.core.process.ProcessOutputException.withPrefix(ProcessOutputException.java:20)
at io.xpipe.ext.proc.util.c.a(SourceFile:145)
at io.xpipe.ext.proc.m.x(SourceFile:249)
at io.xpipe.ext.proc.m.start(SourceFile:196)
at io.xpipe.core.store.ShellStore.validate(ShellStore.java:31)
at io.xpipe.app.storage.DataStoreEntry.validateOrThrow(DataStoreEntry.java:398)
at io.xpipe.app.storage.DataStoreEntry.validate(DataStoreEntry.java:387)
at io.xpipe.ext.proc.env.l.a(SourceFile:37)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$1(ScanAlert.java:158)
at io.xpipe.app.util.BooleanScope.execute(BooleanScope.java:11)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$2(ScanAlert.java:146)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)

**Comment by crschnick** [comment]
Oh well, seems like I need to set up a BSD vm then.

**Comment by ascl00** [comment]
It's easy enough to do! But if you need me to test, I'm happy to test.

**Comment by crschnick** [comment]
Alright, I set up a BSD VM and properly fixed the issue. It was actually getting detected properly but it still added the normal sh dialect.

You can try it out in the latest PTB. (The missing sh icon can be ignored)

**Comment by ascl00** [comment]
Nice, I can confirm it works for me now! Thanks!

**Comment by crschnick** [comment]
This fix is now included in the latest release
