### ISSUE TITLE
Received the following error while importing a Remote Host

### ISSUE THREAD

**Issue by funkywaddle** [xpipe-io/xpipe#149]
### Environment
```
Linux Mint 21.2 x86_64
```

### Version
```
XPipe 1.7.12 for Linux (.deb x86-64)
```

### Action which caused error
```
I was creating another remote host.

Details:
3rd Remote Host
3rd different Identity File
```

### Error
```
Process returned exit code 1:
Error: unknown shorthand flag: 'f' in -f
```

### Stack Trace
```
io.xpipe.core.process.ProcessOutputException: Process returned exit code 1:
Error: unknown shorthand flag: 'f' in -f
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:36)
at io.xpipe.ext.proc.a.a(SourceFile:256)
at io.xpipe.ext.proc.a.readStdoutOrThrow(SourceFile:313)
at io.xpipe.ext.proc.lxd.c.g(SourceFile:73)
at io.xpipe.ext.proc.lxd.c.a(SourceFile:53)
at io.xpipe.ext.proc.lxd.LxdCmdStore.listChildren(SourceFile:69)
at io.xpipe.app.storage.DataStoreEntry.validateOrThrow(DataStoreEntry.java:400)
at io.xpipe.app.storage.DataStoreEntry.validate(DataStoreEntry.java:387)
at io.xpipe.ext.proc.lxd.d.a(SourceFile:14)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$1(ScanAlert.java:158)
at io.xpipe.app.util.BooleanScope.execute(BooleanScope.java:11)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$2(ScanAlert.java:146)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)
```

**Comment by crschnick** [comment]
Which LXD version are you using? Essentially we are trying to query all containers with `lxc list -f csv -c ns`, however I'm not sure from which version onwards that option is supported

**Comment by funkywaddle** [comment]
It is reporting on that server as v3.0.3

**Comment by crschnick** [comment]
Judging from https://github.com/canonical/lxd/releases?page=9, that version is five years old. I'm not sure whether it would make sense to spend some effort to also support that as almost no one will run that

**Comment by crschnick** [comment]
Oh yeah I guess that's reasonable, just from the message without the stack trace it is not apparent where it comes from. I might have to improve that error reporter in the future to also maybe show some context information.
