### ISSUE TITLE
Adding an OPNSense Connection: Shell opener command was unsuccessful: Illegal option -l

### ISSUE THREAD

**Issue by nmcbride** [xpipe-io/xpipe#156]
Connecting into OPNSense and searching for connections created this error. It is specific to `sh`, `bash` works fine.
Looks like `-l` exists on `bash` but not on `sh`.

This may be a FreeBSD thing specifically since that is what OPNSense is based on. On Fedora `sh` has `-l`.

```
io.xpipe.core.process.ProcessOutputException: Shell opener command was unsuccessful:
Illegal option -l
at io.xpipe.core.process.ProcessOutputException.withPrefix(ProcessOutputException.java:14)
at io.xpipe.ext.proc.util.c.a(SourceFile:145)
at io.xpipe.ext.proc.m.x(SourceFile:249)
at io.xpipe.ext.proc.m.start(SourceFile:196)
at io.xpipe.core.store.ShellStore.validate(ShellStore.java:31)
at io.xpipe.app.storage.DataStoreEntry.validateOrThrow(DataStoreEntry.java:398)
at io.xpipe.app.storage.DataStoreEntry.validate(DataStoreEntry.java:387)
at io.xpipe.ext.proc.env.l.a(SourceFile:37)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$1(ScanAlert.java:158)
at io.xpipe.app.util.BooleanScope.execute(BooleanScope.java:11)
at io.xpipe.app.util.ScanAlert$1.lambda$finish$2(ScanAlert.java:146)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)
```

**Comment by crschnick** [comment]
This is related to #147 and should be fixed in the latest release now

**Comment by crschnick** [comment]
Whoops, it seems like I forgot to close this issue. But it should definitely be fixed
