### ISSUE TITLE
Shell did not start up in time

### ISSUE THREAD

**Issue by vonwerderc** [xpipe-io/xpipe#173]
I've been using Xpipe for a few weeks now with no issues, it's been fantastic. Today all of a sudden it can't connect to anything. I keep getting this same error for everything. I can ssh into this server with putty or a command prompt on windows and it works instantly. I'm not sure what is going on. 

`Shell did not start up in time as we did not receive any response. In case the shell is just slow, you can try increasing the timeout value in the settings.

Linux pve2 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64
`

`io.xpipe.core.process.ProcessOutputException: Shell did not start up in time as we did not receive any response. In case the shell is just slow, you can try increasing the timeout value in the settings.

Linux pve2 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Checking what shell type we are in ...
-NoEnumerate a
Shell did not respond in timeout interval. Now we are reading any possible error output and checking whether we are in fish
fish: 
0END

C:\Users\vonwe>
at io.xpipe.core.process.ProcessOutputException.withParagraph(ProcessOutputException.java:14)
at io.xpipe.ext.proc.util.c.a(SourceFile:214)
at io.xpipe.ext.proc.m.x(SourceFile:260)
at io.xpipe.ext.proc.ssh.SshBaseStore$2.x(SourceFile:111)
at io.xpipe.ext.proc.m.start(SourceFile:207)
at io.xpipe.ext.proc.m.prepareIntermediateTerminalOpen(SourceFile:134)
at io.xpipe.ext.proc.m.prepareTerminalOpen(SourceFile:123)
at io.xpipe.app.util.TerminalHelper.open(TerminalHelper.java:32)
at io.xpipe.ext.base.action.LaunchAction$Action.execute(LaunchAction.java:31)
at io.xpipe.app.comp.store.StoreEntryWrapper.executeDefaultAction(StoreEntryWrapper.java:202)
at io.xpipe.app.comp.store.StoreEntryComp.lambda$createSimple$0(StoreEntryComp.java:91)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:40)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)
`

**Comment by crschnick** [comment]
I received one other report like this so it doesn't seem to be an isolated issue. What is very confusing to me is that I didn't actually change anything relating to shell detection. The ssh connection aspect got reworked yes, but that should not cause it. There are also many other people who are using it without any problem. It seems like for a few people nothing works anymore.

Can you run "C:\Users\<User>\AppData\Local\XPipe\app\scripts\xpiped_debug.bat" > C:\Users\<User>\Desktop\xpipe_output.txt in cmd and send me the output file either on discord or per email at [crschnick@xpipe.io](mailto:crschnick@xpipe.io) ?

**Comment by crschnick** [comment]
This is now fixed in 1.7.16
