### ISSUE TITLE
Connect XPipe to ssh-agent?

### ISSUE THREAD

**Issue by faxotherapy** [xpipe-io/xpipe#190]
I have ssh-agent running in background on macOS. Is it possible to make XPipe connect to that ssh-agent so I don't need to input my key passphrase. Thank you.

**Comment by crschnick** [comment]
I think on macos the passphrases are stored in the macos keychain by the ssh agent. So you should be able to make that work by supplying the option `UseKeychain yes` through a custom SSH connection.

I'm not sure whether I want to supply this option by default as some people might not like this behavior of automatically filling passphrases without being asked.

**Comment by crschnick** [comment]
This is now released, let me know whether it works for you.

**Comment by suhrke** [comment]
Hello,
I just installed XPipe 10.0.2 and ssh-agent. Using powershell I can connect to an internet host I can only connect with ssh key. With XPipe it don't work

io.xpipe.core.process.ProcessOutputException: Shell opener command was unsuccessful:
Operation was cancelled
Permission denied, please try again.
Operation was cancelled
Permission denied, please try again.
Operation was cancelled
suhrke@james.suhrke.net: Permission denied (publickey,password).  <<  !!!
at io.xpipe.core.process.ProcessOutputException.withPrefix(ProcessOutputException.java:29)
at io.xpipe.ext.proc.util.f.a(SourceFile:321)
at io.xpipe.ext.proc.l.n(SourceFile:2578)
at io.xpipe.ext.proc.ssh.r.n(SourceFile:88)
at io.xpipe.ext.proc.l.C(SourceFile:489)
at io.xpipe.ext.proc.l.start(SourceFile:225)
at io.xpipe.app.util.ScanAlert$Dialog.lambda$content$11(ScanAlert.java:188)
at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:18)
at io.xpipe.app.util.ScanAlert$Dialog.lambda$content$12(ScanAlert.java:180)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)

What's going wrong?
