### ISSUE TITLE
Can't save files with new 9.2 version most of the time

### ISSUE THREAD

**Issue by pythongod** [xpipe-io/xpipe#267]
- Open a file via right click (Edit with Visual Code)
- Save (or "save as root" extension)
- get Error, see below

- did not get that error with 9.0 and 9.1

Error Messages:
Process returned exit code 1:
dd: failed to open '/home/jack/docker/homepage/config/services.yaml': Permission denied
-bash: line 37: /home/jack/docker/homepage/config/services.yaml: Permission denied

io.xpipe.core.process.ProcessOutputException: Process returned exit code 1:
dd: failed to open '/home/jack/docker/homepage/config/services.yaml': Permission denied
-bash: line 37: /home/jack/docker/homepage/config/services.yaml: Permission denied
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:53)
at io.xpipe.ext.proc.a.a(SourceFile:432)
at io.xpipe.ext.proc.a$2.close(SourceFile:115)
at io.xpipe.app.util.FileBridge.lambda$openIO$5(FileBridge.java:206)
at io.xpipe.app.util.FileBridge.handleWatchEvent(FileBridge.java:99)
at io.xpipe.app.util.FileBridge.lambda$init$0(FileBridge.java:59)
at io.xpipe.app.core.AppFileWatcher$WatchedDirectory.handleWatchEvent(AppFileWatcher.java:189)
at io.xpipe.app.core.AppFileWatcher$WatchedDirectory.update(AppFileWatcher.java:154)
at io.xpipe.app.core.AppFileWatcher.lambda$startWatcher$1(AppFileWatcher.java:75)
at java.lang.Thread.run(Thread.java:1583)

I'm on mac installed with homebrew

**Comment by crschnick** [comment]
So according to the error, it can't open the file. If you open a terminal in that directory, and try to edit the files manually, does that also happen? What are the file permissions on that file? Is that a local file or remote?

**Comment by crschnick** [comment]
So how are you opening the file browser session? You should be able to open any directory as root in xpipe. If you are opening it as a normal user, then according to the permissions this fails as intended.

There should have been no changes to this behavior in 9.2, at least not intentional. Can you try downgrading to 9.1, maybe by downloading a separate portable version, and check this in 9.1?

**Comment by crschnick** [comment]
Yeah so you would either have to change the owner of that file or use the button in the file browser to open a directory as root and edit it in that session.
