### ISSUE TITLE
Terminal Configuration in Settings Fails on Preview with Canary and Stable Installed

### ISSUE THREAD

**Issue by davidldennison** [xpipe-io/xpipe#269]
First off, great job with this app. Very beautifully designed, even the public test build is rock solid. Looking forward to seeing where XPipe goes!

**Issue:**

Using Terminal Canary side loaded with Terminal Stable.  
Ran the terminal config in settings for Terminal preview (as I figured closest to my highest/most used version). Failed with Java exception due to not finding the path.
Tried the Terminal Stable option and command runs. Also works on cmd.

Let me know if you need me to send any additional logs or files! Happy to help!

**Details:**

```
java.io.IOException: Unable to launch terminal Windows Terminal Preview: Process returned exit code 3:
The system cannot find the path specified.
at io.xpipe.app.util.TerminalLauncher.open(TerminalLauncher.java:73)
at io.xpipe.app.util.TerminalLauncher.open(TerminalLauncher.java:43)
at io.xpipe.app.prefs.TerminalCategory.lambda$create$0(TerminalCategory.java:43)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: io.xpipe.core.process.ProcessOutputException: Process returned exit code 3:
The system cannot find the path specified.
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:53)
at io.xpipe.ext.proc.a.a(SourceFile:432)
at io.xpipe.ext.proc.a.discardOrThrow(SourceFile:252)
at io.xpipe.core.process.ShellControl.executeSimpleCommand(ShellControl.java:139)
at io.xpipe.app.terminal.WindowsTerminalType$Preview.launch(WindowsTerminalType.java:77)
at io.xpipe.app.util.TerminalLauncher.open(TerminalLauncher.java:69)
... 5 more
```

**Environment:**

Windows 11 Pro Insider Preview
Evaluation copy. Build 26212.ge_prerelease.240503-1218

Windows Terminal Canary
Version: 1.22.1341.0
"C:\Program Files\WindowsApps\Microsoft.WindowsTerminalCanary_1.22.1341.0_x64__8wekyb3d8bbwe"

Windows Terminal
Version: 1.20.11271.0
"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.20.11271.0_x64__8wekyb3d8bbwe"

Windows 11 Insider Program on Latest Canary - 26212.ge_prerelease 
XPipe Community 10.0

**Comment by crschnick** [comment]
I didn't even know that there was a canary build. I can add support for that, shouldn't be too different from the other windows terminal implementations.

**Comment by crschnick** [comment]
This is now added in https://github.com/xpipe-io/xpipe/releases/tag/9.3
