### ISSUE TITLE
VNC with Raspberry Pi 5 is not supported

### ISSUE THREAD

**Issue by FDelporte** [xpipe-io/xpipe#280]
When connecting with VNC to a Raspberry Pi 5 with the latest OS, the following error is thrown:

```
java.lang.RuntimeException: com.shinyhut.vernacular.client.exceptions.NoSupportedSecurityTypesException: The server does not support any VNC security types supported by this client
```

It is known that VNC on RPi5 is different: https://help.realvnc.com/hc/en-us/articles/14110635000221-Raspberry-Pi-5-Bookworm-and-RealVNC-Connect

FYI, TigerVNC is compatible with RPi5.

OS info:

```
$ uname -a
Linux pi5 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
```

**Comment by crschnick** [comment]
I will have to look up which security types it supports. I already prepared for this somewhat by forking and manually implementing more secure authentication measures at https://github.com/xpipe-io/vernacular-vnc/tree/aeseax, but that is not fully tested yet.

I'm also not sure what kind of settings you have available on the VNC server that you can tweak until I release that version. The idea in xpipe is to always tunnel and authenticate via SSH, so even unsecure authentication measures are secure when you use them with xpipe and don't publicly expose the VNC port.

**Comment by crschnick** [comment]
It seems like running a wayvnc server isn't that trivial in a VM.

Could you list the available security types for your server? They should look something like this: None, VncAuth, Plain, TLSNone, TLSVnc, TLSPlain, X509None, X509Vnc, X509Plain, RA2, RA2ne, RA2_256, RA2ne_256. They will probably be in some kind of config

**Comment by FDelporte** [comment]
> Could you list the available security types for your server?

That's out of my knowledge ;-) This seems to be the source repo for this VNC server in Raspberry Pi OS: https://github.com/any1/wayvnc/tree/master/protocols

**Comment by crschnick** [comment]
Alright, I managed set it up somehow. Can you share the [config](https://manpages.opensuse.org/Tumbleweed/wayvnc/wayvnc.1.en.html#CONFIGURATION) contents so I can reproduce this on my end?

**Comment by crschnick** [comment]
So even if there is no config file, you can manually create one at `~/.config/wayvnc/config`.

If you create one with `enable_auth=false` as content, it *should* work for now. That is sufficient if you're using it only locally and have not exposed it to the public.

**Comment by crschnick** [comment]
Alright so I worked a bit on the VNC auth part and added some more security types. I'm not sure whether that is enough for wayvnc, but you can try it out that https://github.com/xpipe-io/xpipe-ptb.

**Comment by FDelporte** [comment]
Hi Christopher, thanks for the update! I only have limited time to test as I'm approaching our holiday, in September I will have more time...



I have the same error with this version:



java.lang.RuntimeException: VNC server requires unsupported advanced encrypted authentication. Note that  insecure authentication methods for the server as all communication is encrypted anyway.

at io.xpipe.ext.proc.vnc.f.a(SourceFile:136)

at com.shinyhut.vernacular.client.VernacularClient.notifyErrorListeners(VernacularClient.java:290)

at com.shinyhut.vernacular.client.VernacularClient.handleError(VernacularClient.java:284)

at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:81)

at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:52)

at io.xpipe.ext.proc.vnc.f.init(SourceFile:238)

at io.xpipe.app.browser.session.BrowserAbstractSessionModel.openSync(BrowserAbstractSessionModel.java:30)

at io.xpipe.ext.proc.vnc.h$1.execute(SourceFile:71)

at io.xpipe.ext.base.action.LaunchStoreAction$Action.execute(LaunchStoreAction.java:105)

at io.xpipe.app.comp.store.StoreEntryWrapper.runAction(StoreEntryWrapper.java:246)

at io.xpipe.app.comp.store.StoreEntryWrapper.executeDefaultAction(StoreEntryWrapper.java:235)

at io.xpipe.app.comp.store.StoreEntryComp.lambda$createSimple$0(StoreEntryComp.java:106)

at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)

at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)

at java.lang.VirtualThread.run(VirtualThread.java:309)

Caused by: com.shinyhut.vernacular.client.exceptions.NoSupportedSecurityTypesException: The server does not support any VNC security types supported by this client

at com.shinyhut.vernacular.protocol.handshaking.SecurityTypeNegotiator.resolve(SecurityTypeNegotiator.java:41)

at com.shinyhut.vernacular.protocol.handshaking.SecurityTypeNegotiator.negotiate(SecurityTypeNegotiator.java:25)

at com.shinyhut.vernacular.protocol.handshaking.Handshaker.handshake(Handshaker.java:24)

at com.shinyhut.vernacular.client.VernacularClient.createSession(VernacularClient.java:279)

at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:72)

... 11 more



Best regards

Frank Delporte




Want to have coding-fun? 

Check my blog https://webtechie.be/ and book "Getting started with Java on Raspberry Pi" on https://webtechie.be/books/













---- On Fri, 19 Jul 2024 20:19:40 +0200 Christopher Schnick ***@***.***> wrote ---





Alright so I worked a bit on the VNC auth part and added some more security types. I'm not sure whether that is enough for wayvnc, but you can try it out that https://github.com/xpipe-io/xpipe-ptb.

**Comment by crschnick** [comment]
What version of wayvnc is running for you? I jumped over more outdated authentication schemes and implemented the newest one. Looking at wayvnc releases. that should only be supported from 0.7.0 onwards.

There are also now instructions for wayvnc how to enable rsa authentication if it's not enabled yet: https://github.com/any1/wayvnc?tab=readme-ov-file#rsa-aes by creating the config at $HOME/.config/wayvnc/config

**Comment by FDelporte** [comment]
will put this on my agenda for start of September. maybe we can do some "pair debugging" at that time?











---- On Mon, 22 Jul 2024 08:40:17 +0200 Christopher Schnick ***@***.***> wrote ---





What version of wayvnc is running for you? I jumped over more outdated authentication schemes and implemented the newest one. Looking at wayvnc releases. that should only be supported from 0.7.0 onwards.

There are also now instructions for wayvnc how to enable rsa authentication if it's not enabled yet: https://github.com/any1/wayvnc?tab=readme-ov-file#rsa-aes by creating the config at $HOME/.config/wayvnc/config

**Comment by crschnick** [comment]
Yeah we can do that, just let me know when you have some time

**Comment by crschnick** [comment]
I think from your error message, did you run the correct xpipe version? Note that the normal release and PTB release are different apps with different names, they don't override each other. The PTB application window should also look different.

In addition I published another updated PTB at https://github.com/xpipe-io/xpipe-ptb/releases/tag/10.2-8 that will actually list the missing security types if it fails.

Maybe you can try that out some time when you're not too busy.

**Comment by crschnick** [comment]
You can try out the latest PTB at https://github.com/xpipe-io/xpipe-ptb, I implemented support for the required authentication methods.

Note that the PTB is a different app, so you also have to launch the XPipe PTB app. It does not override the normal XPipe installation.

**Comment by FDelporte** [comment]
with 11.2-5 a step closer... ;-)

```
java.lang.RuntimeException: com.shinyhut.vernacular.client.exceptions.AuthenticationFailedException: Authentication failed. The server returned the following extra information: Invalid username or password
at io.xpipe.ext.proc.vnc.f.a(SourceFile:140)
at com.shinyhut.vernacular.client.VernacularClient.notifyErrorListeners(VernacularClient.java:293)
at com.shinyhut.vernacular.client.VernacularClient.handleError(VernacularClient.java:287)
at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:81)
at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:52)
at io.xpipe.ext.proc.vnc.f.init(SourceFile:237)
at io.xpipe.app.browser.session.BrowserAbstractSessionModel.openSync(BrowserAbstractSessionModel.java:30)
at io.xpipe.ext.proc.vnc.h$1.execute(SourceFile:72)
at io.xpipe.app.comp.store.StoreEntryWrapper.runAction(StoreEntryWrapper.java:248)
at io.xpipe.app.comp.store.StoreEntryWrapper.executeDefaultAction(StoreEntryWrapper.java:237)
at io.xpipe.app.comp.store.StoreEntryComp.lambda$createSimple$0(StoreEntryComp.java:104)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: com.shinyhut.vernacular.client.exceptions.AuthenticationFailedException: Authentication failed. The server returned the following extra information: Invalid username or password
at com.shinyhut.vernacular.protocol.handshaking.Handshaker.handshake(Handshaker.java:29)
at com.shinyhut.vernacular.client.VernacularClient.createSession(VernacularClient.java:279)
at com.shinyhut.vernacular.client.VernacularClient.start(VernacularClient.java:72)
... 10 more
```

**Comment by crschnick** [comment]
Does it work when you add the relaxed encryption setting to the config? In theory this issue shouldn't be related to the new implementation.

Does that VNC server require a username as well or only a password?

**Comment by FDelporte** [comment]
Sorry, same error with `relax_encryption=true`

**Comment by crschnick** [comment]
I pushed another PTB to hopefully fix the authentication issue

**Comment by FDelporte** [comment]
we have a winner!!! ;-)
I got a popup box asking for the username, and then successful VNC window in XPipe.
I double checked and authentication is on, relax is off, so it's in the "normal default mode"

![Screenshot 2024-09-05 at 17 30 23](https://github.com/user-attachments/assets/eb41705d-433b-4a40-9ab8-3c9cd1d24170)

**Comment by crschnick** [comment]
You can set the username in xpipe when you edit the VNC connection.

Also, does the file drop work now?

**Comment by FDelporte** [comment]
1/ indeed, adding username in vnc connection settings solves the popup
2/ file drop: no error, but nothing happens...

**Comment by crschnick** [comment]
Is the $DISPLAY variable set in your wayland vnc session?

**Comment by FDelporte** [comment]
How to check/change that?

**Comment by crschnick** [comment]
just `echo $DISPLAY` in a terminal in your VNC session

**Comment by FDelporte** [comment]
```
$ echo $DISPLAY
:0
```

**Comment by crschnick** [comment]
what port is that VNC server running on?

**Comment by FDelporte** [comment]
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      2143/cupsd          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      905/sshd: /usr/sbin 
tcp6       0      0 ::1:631                 :::*                    LISTEN      2143/cupsd          
tcp6       0      0 :::22                   :::*                    LISTEN      905/sshd: /usr/sbin 
tcp6       0      0 :::5900                 :::*                    LISTEN      7376/wayvnc         
udp        0      0 0.0.0.0:631             0.0.0.0:*                           2145/cups-browsed   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           689/avahi-daemon: r 
udp        0      0 0.0.0.0:52460           0.0.0.0:*                           689/avahi-daemon: r 
udp6       0      0 :::53195                :::*                                689/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                689/avahi-daemon: r 
```

**Comment by crschnick** [comment]
Hmm ... ideally that should work though with the file opener.

Do other desktop features work? E.g. if you go to xpipe -> New ... -> Desktop -> Desktop application and run some graphical application that is installed on the system, does that show?

**Comment by crschnick** [comment]
What about `echo $WAYLAND_DISPLAY `. I think right now xpipe only uses the x11 display variable which might not apply here.

**Comment by crschnick** [comment]
I released another PTB that now also sets `WAYLAND_DISPLAY `. Maybe that will help

**Comment by crschnick** [comment]
This is now released in 11.2. About the file opener, I guess you can open a separate issue if that still persists.

**Comment by crschnick** [comment]
Were you able to test the file open again?

**Comment by FDelporte** [comment]
File drag and drop to VNC just tested with 11.3 but is not working

**Comment by crschnick** [comment]
Hmm, if you want, we can debug this again
