### ISSUE TITLE
windows 11 - clicking host in file section gives error (ptb

### ISSUE THREAD

**Issue by tolgaulas** [xpipe-io/xpipe#310]
java.lang.UnsupportedOperationException: System shell does not support file system interaction
```
java.lang.UnsupportedOperationException: System shell does not support file system interaction
at io.xpipe.core.store.ConnectionFileSystem.open(ConnectionFileSystem.java:42)
at io.xpipe.app.browser.fs.OpenFileSystemModel.lambda$init$2(OpenFileSystemModel.java:89)
at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:18)
at io.xpipe.app.browser.fs.OpenFileSystemModel.init(OpenFileSystemModel.java:84)
at io.xpipe.app.browser.session.BrowserSessionModel.openFileSystemSync(BrowserSessionModel.java:93)
at io.xpipe.app.browser.session.BrowserSessionModel.lambda$openFileSystemAsync$4(BrowserSessionModel.java:76)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)
```

(also sent reports with `report error` within the app)

![image](https://github.com/user-attachments/assets/fd7d9dfd-f123-4149-95ec-910aa76ab115)

**Comment by crschnick** [comment]
What kind of shell is that?

Usually that error message means that an unsupported shell is running on the system

**Comment by crschnick** [comment]
I was referring to the shell of the remote system you're connecting to

**Comment by crschnick** [comment]
So the report you sent doesn't contain the necessary information on why this fails. Either this is a restricted bash (rbash) instance or the shell type is not recognized correctly as bash.

You can try to go to Settings -> Troubleshoot -> Launch in debug mode and share the output of when it fails. You can send that via email for example.

**Comment by crschnick** [comment]
Oh I see. I think I can change the error message in that case to be more accurate

**Comment by crschnick** [comment]
The error message has now been improved in the latest PTB
