### ISSUE TITLE
java.nio.file.FileSystemException: /Users/user/Desktop: Operation not permitted

### ISSUE THREAD

**Issue by casperghst42** [xpipe-io/xpipe#337]
xPipe should not require access to ~/Desktop and it should not throw an exception when it doesn't have access. 

java.nio.file.FileSystemException: /Users/user/Desktop: Operation not permitted
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:461)
at java.nio.file.Files.newDirectoryStream(Files.java:481)
at java.nio.file.Files.list(Files.java:3772)
at io.xpipe.ext.proc.rdp.b.create(SourceFile:30)
at io.xpipe.app.util.ScanAlert.lambda$showForShellStore$1(ScanAlert.java:66)
at io.xpipe.app.util.ScanAlert$Dialog.lambda$content$11(ScanAlert.java:205)
at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:18)
at io.xpipe.app.util.ScanAlert$Dialog.lambda$content$12(ScanAlert.java:196)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)

**Comment by crschnick** [comment]
Yep, I will fix that for the next release.

**Comment by crschnick** [comment]
This is now fixed in the latest release
