### ISSUE TITLE
Sudoers Issue

### ISSUE THREAD

**Issue by ramzimalhas** [xpipe-io/xpipe#380]
io.xpipe.core.process.ProcessOutputException: Process did not start up properly and had to be killed:
ramzimalhas is not in the sudoers file.
This incident has been reported to the administrator.
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:59)
at io.xpipe.ext.proc.b.a(SourceFile:330)
at io.xpipe.ext.proc.b.readStdoutOrThrow(SourceFile:259)
at io.xpipe.ext.proc.k8s.f.aL(SourceFile:119)
at io.xpipe.ext.proc.k8s.d.listChildren(SourceFile:48)
at io.xpipe.app.storage.DataStorage.refreshChildren(DataStorage.java:384)
at io.xpipe.app.storage.DataStorage.refreshChildren(DataStorage.java:368)
at io.xpipe.ext.proc.k8s.n.scan(SourceFile:22)
at io.xpipe.app.util.ScanDialog.lambda$finish$1(ScanDialog.java:85)
at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:22)
at io.xpipe.app.util.ScanDialog.lambda$finish$2(ScanDialog.java:69)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:329)
Suppressed: io.xpipe.core.process.ProcessOutputException: Wait for process exit timed out:
ramzimalhas is not in the sudoers file.
This incident has been reported to the administrator.
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:59)
at io.xpipe.ext.proc.d.close(SourceFile:119)
at io.xpipe.ext.proc.b.readStdoutOrThrow(SourceFile:237)
... 11 more

**Comment by crschnick** [comment]
If not, what is the output of `kubectl config current-context` for you as a normal user?

**Comment by crschnick** [comment]
How did you modify the .zshrc file and PATH?

Just from breaking the .zshrc you shouldn't be able to break your system that much. At most, any of such problem can be fixed by wiping the zshrc file.

If you can somehow enable it, I would try to log in directly as root: https://support.apple.com/en-us/102367

If that does not work, I would just do this: https://support.apple.com/guide/mac-help/erase-your-mac-mchl7676b710/15.0/mac/15.0 

From your description it does not sound like this just being a sudoers file issue, they are likely multiple issues all over the place

**Comment by crschnick** [comment]
About XPipe being the right solution for you, I think I have to mention that it has nothing to do with your configuration. If you use tools such as nix or something else doesn't really matter. It is just designed to give you an easy overview and access to any servers and shells you have. It works on top of your existing setup, independently of how you configured your system.

**Comment by crschnick** [comment]
I hope you were able to fix these issues. I think I can close this issue.

If you have anything else, feel free to open another one again
