### ISSUE TITLE
java.nio.file.InvalidPathException

### ISSUE THREAD

**Issue by ErickPH** [xpipe-io/xpipe#392]
While running Xpipe 13.4.3 for the first time. If I hot IGNORE, then it continues normally.

Please let me know if you need more logs/files

OS: Windows 10 Pro 22H2

java.nio.file.InvalidPathException: Trailing char < > at index 27: C:\WINDOWS\system32\cmd.exe /K

java.nio.file.InvalidPathException: Trailing char < > at K
at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:194)
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
at java.nio.file.Path.of(Path.java:148)
at io.xpipe.ext.proc.dialect.a$2.localCommand(SourceFile:598)
at io.xpipe.ext.proc.dialect.a$2.loginCommand(SourceFile:619)
at io.xpipe.ext.proc.env.r$1.a(SourceFile:75)
at io.xpipe.core.process.CommandBuilder.lambda$addAll$7(CommandBuilder.java:165)
at io.xpipe.core.process.CommandBuilder.buildBaseParts(CommandBuilder.java:246)
at io.xpipe.core.process.CommandBuilder.buildBase(CommandBuilder.java:233)
at io.xpipe.core.process.CommandBuilder.buildFull(CommandBuilder.java:272)
at io.xpipe.ext.proc.m.p(SourceFile:574)
at io.xpipe.ext.proc.m.D(SourceFile:541)
at io.xpipe.ext.proc.m.start(SourceFile:255)
at io.xpipe.app.ext.ShellStore.validate(ShellStore.java:53)
at io.xpipe.app.storage.DataStoreEntry.validateOrThrow(DataStoreEntry.java:530)
at io.xpipe.ext.proc.env.t.scan(SourceFile:75)
at io.xpipe.app.util.ScanDialog.lambda$finish$1(ScanDialog.java:85)
at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:22)
at io.xpipe.app.util.ScanDialog.lambda$finish$2(ScanDialog.java:69)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:42)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:329)

**Comment by crschnick** [comment]
What is the value of `%ComSpec%` for you?

**Comment by ErickPH** [comment]
This is the value
ComSpec=C:\WINDOWS\system32\cmd.exe /K

**Comment by crschnick** [comment]
Is there any particular reason why the /K is there? To not close cmd windows automatically?

I have to look up whether this is even supported in ComSpec, trailing arguments. But I should be able to fix that regardless

**Comment by ErickPH** [comment]
Ok, I recalled that some PowerShell things that I was doing, needed that for some debugging of system calls.
I have now removed /K and Xpipe starts successfully.

**Comment by crschnick** [comment]
So I'm not sure whether this passing of arguments is even supported in general. You might be breaking other programs as well with that.

**Comment by ErickPH** [comment]
@crschnick I bet you are right.
BTW /K makes cmd stop after executing bat files and will not close the terminal window at exit. normal behavior is to close terminal window after running some command.

So, me bad here. 
This can be closed.

**Comment by crschnick** [comment]
This is now fixed in the latest release by making it more robust
