### ISSUE TITLE
Temporary directory permission issues

### ISSUE THREAD

**Issue by Go2Engle** [xpipe-io/xpipe#59]
When trying to connect to root ssh connection I get the below error.
```
io.xpipe.core.process.ProcessOutputException: Process returned exit code 1:
-bash: line 13: /tmp/xpipe/exec/askpass-1169274321.sh.1.txt: Permission denied
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:34)
at io.xpipe.ext.proc.a.a(SourceFile:280)
at io.xpipe.ext.proc.a.discardOrThrow(SourceFile:346)
at io.xpipe.core.process.CommandControl.execute(CommandControl.java:41)
at io.xpipe.ext.procx.dialect.c.prepareAskpassContent(SourceFile:690)
at io.xpipe.app.util.ScriptHelper.createAskPassScript(ScriptHelper.java:161)
at io.xpipe.app.util.ScriptHelper.createAskPassScript(ScriptHelper.java:139)
at io.xpipe.app.util.ScriptHelper.createAskPassScript(ScriptHelper.java:127)
at io.xpipe.ext.procx.util.a.a(SourceFile:45)
at io.xpipe.ext.procx.util.a.a(SourceFile:118)
at io.xpipe.ext.procx.g.start(SourceFile:1205)
at io.xpipe.ext.procx.g.prepareIntermediateTerminalOpen(SourceFile:94)
at io.xpipe.ext.procx.g.prepareTerminalOpen(SourceFile:89)
at io.xpipe.core.store.ShellStore.prepareLaunchCommand(ShellStore.java:27)
at io.xpipe.ext.base.action.LaunchAction$Action.execute(LaunchAction.java:29)
at io.xpipe.app.comp.storage.store.StoreEntryWrapper.executeDefaultAction(StoreEntryWrapper.java:197)
at io.xpipe.app.comp.storage.store.StoreEntryComp.lambda$createSimple$1(StoreEntryComp.java:77)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$0(ThreadHelper.java:18)
at java.lang.Thread.run(Thread.java:1589)
```

The user account does not have access to /tmp without sudo rights. Could that be the possible cause for this?

**Comment by crschnick** [comment]
Yes, it is sometimes necessary to create some shell scripts. That is done in /tmp by default as I assumed that users would have write access to that. Does your user not have any rights or just not for /tmp ?

How exactly does the connection chain look like here? Is it possible to create an elevated shell environment first, and create the ssh connection in that so that everything is done as root?

**Comment by Go2Engle** [comment]
yeah that sounds like a perfect solution!

**Comment by crschnick** [comment]
Can you try whether this build works for you: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.3.2

It should fall back to a subdirectory in the user home in case it doesn't have all permissions for /tmp.

**Comment by Go2Engle** [comment]
still getting the below =[

```
io.xpipe.core.process.ProcessOutputException: Process returned exit code 1:
-bash: line 27: /tmp/xpipe/exec/askpass-1331980410.sh.1.txt: Permission denied
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:34)
at io.xpipe.ext.proc.a.a(SourceFile:280)
at io.xpipe.ext.proc.a.discardOrThrow(SourceFile:346)
at io.xpipe.core.process.CommandControl.execute(CommandControl.java:41)
at io.xpipe.ext.procx.dialect.c.prepareAskpassContent(SourceFile:691)
at io.xpipe.app.util.ScriptHelper.createAskPassScript(ScriptHelper.java:161)
at io.xpipe.app.util.ScriptHelper.createAskPassScript(ScriptHelper.java:139)
at io.xpipe.app.util.ScriptHelper.createAskPassScript(ScriptHelper.java:127)
at io.xpipe.ext.procx.util.a.a(SourceFile:45)
at io.xpipe.ext.procx.util.a.a(SourceFile:118)
at io.xpipe.ext.procx.g.prepareIntermediateTerminalOpen(SourceFile:107)
at io.xpipe.ext.procx.g.prepareTerminalOpen(SourceFile:89)
at io.xpipe.core.store.ShellStore.prepareLaunchCommand(ShellStore.java:27)
at io.xpipe.ext.base.action.LaunchAction$Action.execute(LaunchAction.java:29)
at io.xpipe.app.comp.storage.store.StoreEntryWrapper.executeDefaultAction(StoreEntryWrapper.java:197)
at io.xpipe.app.comp.storage.store.StoreEntryComp.lambda$createSimple$1(StoreEntryComp.java:77)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$0(ThreadHelper.java:18)
at java.lang.Thread.run(Thread.java:1589)
```

**Comment by crschnick** [comment]
Hmm ... what is the exit code of `test -r /tmp && test -w /tmp && test -x /tmp` for your user? That is what this build is checking

**Comment by Go2Engle** [comment]
looks like exit code for that is `0`. So I checked again and the user does have permissions to the `/tmp` folder(my bad there, I should have fully checked that 🤦‍♂️) but it looks like the files within the folder are owned by `root`? do you think that could be causing the issue?

![image](https://github.com/xpipe-io/xpipe/assets/15621391/84655c7f-8bf7-47a3-b1de-12aed28977fe)

**Comment by crschnick** [comment]
I see, I will just rewrite the entire tempory directory logic to be bullet-proof as there are also a few other issues with it.

**Comment by crschnick** [comment]
Alright, I updated the build at https://github.com/xpipe-io/xpipe_staging/releases/tag/1.3.2 to now be more robust with regards to temporary directory handling. So you can try that out

**Comment by Go2Engle** [comment]
We are golden now!

PS: If anyone else does have this issue you will first need to manually `sudo rm -rf /tmp/xpipe` to remove stuff that was previously created, or you will still have the previous errors.

**Comment by crschnick** [comment]
Your suggestion of putting the files into the user home directory actually makes more sense, so I switched the logic around in 1.3.2. It will put the files into ~/.xpipe/temp by default and if by some weird configuration you don't have permissions for that directory, it will use /tmp.

(In case you downloaded the staging release, note that it is a incompatible version to the normal releases and won't get updates. So you would have to download and install a proper release again. I am in the process of completely separating both types of installation so in the future you can have staging and normal releases side by side.)

**Comment by Go2Engle** [comment]
Awesome ok sounds good! I'll do a manual re-install then!
