### ISSUE TITLE
Error: Set-PSReadLineOption: command not found

### ISSUE THREAD

**Issue by Drynael** [xpipe-io/xpipe#82]
When i try adding new Connections i encounter following error:

```io.xpipe.core.process.ProcessOutputException: Shell did not start up in time:
Linux [hostname] 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
-bash: line 2: Set-PSReadLineOption: command not found
-NoEnumerate a
Checking whether we are in fish
fish


C:\Users\[Username]>
at io.xpipe.core.process.ProcessOutputException.withPrefix(ProcessOutputException.java:14)
at io.xpipe.ext.proc.util.b.a(SourceFile:151)
at io.xpipe.ext.proc.k.k(SourceFile:237)
at io.xpipe.ext.proc.ssh.SshStore$1.k(SourceFile:142)
at io.xpipe.ext.proc.k.start(SourceFile:159)
at io.xpipe.core.store.ShellStore.validate(ShellStore.java:68)
at io.xpipe.ext.proc.ssh.SshStore.validate(SourceFile:89)
at io.xpipe.ext.proc.ssh.SshConfigStore.validate(SourceFile:39)
at io.xpipe.app.storage.DataStoreEntry.refresh(DataStoreEntry.java:259)
at io.xpipe.ext.proc.ssh.c.b(SourceFile:24)
at io.xpipe.app.util.ScanAlert.lambda$show$8(ScanAlert.java:113)
at io.xpipe.app.util.BusyProperty.execute(BusyProperty.java:10)
at io.xpipe.app.util.ScanAlert.lambda$show$9(ScanAlert.java:107)
at java.lang.VirtualThread.run(VirtualThread.java:305)
at java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:177)
at jdk.internal.vm.Continuation.enter0(Continuation.java:327)
at jdk.internal.vm.Continuation.enter(Continuation.java:320)
```

The connection keeps failing:
![image](https://github.com/xpipe-io/xpipe/assets/15029013/be692118-d123-40aa-922e-f705eb7c1529)

XPipe Version:
![image](https://github.com/xpipe-io/xpipe/assets/15029013/4ec6a417-0042-4960-9060-5b51296a012b)
Windows Version:
![image](https://github.com/xpipe-io/xpipe/assets/15029013/45689200-21e8-41f3-8f41-4d86d172c487)

**Comment by crschnick** [comment]
That error message can usually be ignored, it is just there to disable all possible histories as we don't want to fill the shell history with commands. As we don't know what shell we are in in the beginning, it will just blindly execute all history disabling commands for posix shells and powershell.

I have the suspicion that this error is caused by not waiting long enough for the shell to start up. What you can try to do is use this test build: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.5.3
It already contains various bug fixes and better handling of the timeout, including a new setting to increase it.

**Comment by crschnick** [comment]
This should now be fixed as we no longer call anything related to Set-PSReadLineOption
