### ISSUE TITLE
xpipe  stopped working after linux update

### ISSUE THREAD

**Issue by DaisyF8** [xpipe-io/xpipe#97]
FYI
My working portable xpipe (xpipe daemon mode tray) stopped working after a manjaro update.  I then update xpipe with AUR (non portable) but same error.

error

`java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.MissingNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.MissingNode and com.fasterxml.jackson.databind.node.ObjectNode are in module com.fasterxml.jackson.databind@2.15.2 of loader 'app')`

trace

```
java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.MissingNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.MissingNode and com.fasterxml.jackson.databind.node.ObjectNode are in module com.fasterxml.jackson.databind@2.15.2 of loader 'app')
at io.xpipe.app.prefs.JsonStorageHandler.getContent(JsonStorageHandler.java:36)
at io.xpipe.app.prefs.JsonStorageHandler.loadObject(JsonStorageHandler.java:69)
at io.xpipe.app.prefs.JsonStorageHandler.loadObject(JsonStorageHandler.java:62)
at com.dlsc.preferencesfx.model.Setting.loadSettingValue(Setting.java:689)
at com.dlsc.preferencesfx.model.PreferencesFxModel.lambda$loadSettingValues$7(PreferencesFxModel.java:213)
at java.util.ArrayList.forEach(ArrayList.java:1596)
at com.dlsc.preferencesfx.model.PreferencesFxModel.loadSettingValues(PreferencesFxModel.java:209)
at io.xpipe.app.prefs.AppPreferencesFx.loadSettings(AppPreferencesFx.java:59)
at io.xpipe.app.prefs.AppPrefs.init(AppPrefs.java:379)
at io.xpipe.app.core.mode.BaseMode.onSwitchTo(BaseMode.java:50)
at io.xpipe.app.core.mode.OperationMode.set(OperationMode.java:273)
at io.xpipe.app.core.mode.OperationMode.switchTo(OperationMode.java:142)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:123)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:24)
at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
at picocli.CommandLine.execute(CommandLine.java:2170)
at io.xpipe.app.launcher.LauncherCommand.runLauncher(LauncherCommand.java:64)
at io.xpipe.app.core.mode.OperationMode.init(OperationMode.java:114)
at io.xpipe.app.Main.main(Main.java:15)
```

**Comment by crschnick** [comment]
Hmm, it seems like the settings loading fails. The cause of that should be the file in `~/.xpipe/settings`. Can you share the file contents of it?

**Comment by crschnick** [comment]
I was able to fix the settings loading logic to be more robust and not crash on such an error. I will release this fix in 1.7.4.

Anyways, it's very odd to have a settings corruption like this. Did you check your hard drive for errors? A system update shouldn't break this, only if somehow other data got corrupted along the way.

**Comment by DaisyF8** [comment]
Sorry to take so long to provide feedback.

The original ~/.xpipe/settings/preferences.json has/had size 0, so your suggestion about corruption stands even though I don't have any other type of problem.  I'll keep an eye out but nothing further at the moment.  I must remark that I'm a casual user who for instance months ago didn't even know or find out how to start xpipe in daemon mode (see our earlier convo, I think in Discord but not sure). So if I signal a problem, take it with a grain of salt :)

I updated to xpipe-ptb (same type of error-message window on first launch, window auto closed before I could look at the error. On second launch xpipe was okay) and added my servers. For my use-case xpipe is a godsend because even when I lose my settings it's so easy to add them.

Best of luck with going full-time.

**Comment by crschnick** [comment]
Alright, maybe I forgot to mention it but you can fix the issue for now by just deleting the empty file.

The PTB initial error is actually a completely different issue that I also encountered today, that one will be fixed for the full release. Note that the PTB works on a different set of configuration files in `~/.xpipe-ptb`, so you shouldn't really use it for your main use cases as the data it does not automatically transfer to normal releases. It is really just made for testing things.

Version 1.7.4 should be released tomorrow and it will include proper fixes for everything. Also thanks for the encouragement, I am hopeful that everything will work out.

**Comment by DaisyF8** [comment]
Thx :)
